x-postgres-common:
  &postgres-common
  image: postgres:14.2
  user: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: onelab
  volumes:
    - onelab_psql:/var/lib/postgresql/data
  ports:
    - 5432:5432
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready" ]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres:
    <<: *postgres-common
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    

volumes:
  onelab_psql:
    external: true
