SERVER_ADDRESS: ":9090"
DB_NAME: "onelab"
DB_USER: "postgres"
DB_PASS: "postgres"
DB_HOST: "localhost"
DB_PORT: "5432"
DB_MIGRATIONS_PATH: "file://internal/storage/postgre/migrations"
JWT_KEY: "61feea3b-ca52-44bb-a8e1-b53eefad5cd9"
