package main

import (
	"context"
	"log"

	"github.com/manarakozhamuratova/one-lab-task2/config"
	_ "github.com/manarakozhamuratova/one-lab-task2/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/manarakozhamuratova/one-lab-task2/internal/handler"
	"github.com/manarakozhamuratova/one-lab-task2/transport/httpserver"
)

// @title Manar Super API
// @version 1.0
// @description This is my first swagger documentation.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @host localhost:9090
func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	ctx := context.Background()
	cfg, err := config.ParseYAML()
	if err != nil {
		return err
	}
	handler := handler.NewHandler(cfg, nil)
	server := httpserver.NewServer(cfg, handler)
	server.StartHTTPServer(ctx)
	return nil
}
