definitions:
  model.User:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is my first swagger documentation.
  termsOfService: http://swagger.io/terms/
  title: Manar Super API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Создание пользователя
      operationId: CreateOrder
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses: {}
      summary: Создание пользователя
      tags:
      - user
swagger: "2.0"
